- hosts: localhost
  tasks:
  - name: download file and unarchive to the local server
    unarchive: src=http://www-eu.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
               dest=/home/ec2-user
               creates=/home/ec2-user/apache-maven-3.5.0
               copy=no
